spring:
  application:
    name: EUREKA
--- #注意这里是三个"减号"
spring:
  profiles: eureka1
  security:
    user:
      name: admin
      password: 123123
server:
  port: 8001
eureka:
  instance:
    hostname: eureka1
    prefer-ip-address: true #以IP地址注册到服务中心，相互注册使用IP地址
    instanceId: ${spring.cloud.client.ip-address}:${server.port}
  client:
    serviceUrl:
      defaultZone: http://admin:123123@eureka2:8002/eureka/,http://admin:123123@eureka3:8003/eureka/
    fetchRegistry: true
    registerWithEureka: true
  server : 
    enableSelfPreservation : false    
---
spring:
  profiles: eureka2
  security:
    user:
      name: admin
      password: 123123
server:
  port: 8002
eureka:
  instance:
    hostname: eureka2
    prefer-ip-address: true #以IP地址注册到服务中心，相互注册使用IP地址
    instanceId: ${spring.cloud.client.ip-address}:${server.port}
  client:
    serviceUrl:
      defaultZone: http://admin:123123@eureka1:8001/eureka/,http://admin:123123@eureka3:8003/eureka/
    fetchRegistry: true
    registerWithEureka: true
  server : 
    enableSelfPreservation : false   
---
spring:
  profiles: eureka3
  security:
    user:
      name: admin
      password: 123123
server:
  port: 8003
eureka:
  instance:
    hostname: eureka3
    prefer-ip-address: true #以IP地址注册到服务中心，相互注册使用IP地址
    instanceId: ${spring.cloud.client.ip-address}:${server.port}
  client:
    serviceUrl:
      defaultZone: http://admin:123123@eureka1:8001/eureka/,http://admin:123123@eureka2:8002/eureka/
    fetchRegistry: true
    registerWithEureka: true
  server : 
    enableSelfPreservation : false   