server:
  port: 8765
  servlet : 
    context-path : /service-feign
spring:
  application:
    name: service-feign
  cloud : #指定配置中心
    config : 
      label: SpringcloudConfig #分支的名字
      profile: ${spring.profiles.active}
      #uri: http://localhost:8888
      discovery:
        enabled: true #是从配置中心读取文件
        serviceId: config-server #配置中心的servieId，即服务名   
#healthport: 11102
#当配置中心的值变了之后，需要调用这个去刷新 http://localhost:8765/service-feign/actuator/refresh
 