eureka:
  client:
    serviceUrl:
      defaultZone: http://admin:123123@eureka1:8001/eureka/,http://admin:123123@eureka2:8002/eureka/,http://admin:123123@eureka3:8003/eureka/
  instance:
    prefer-ip-address: true #以IP地址注册到服务中心，相互注册使用IP地址
    instanceId: ${spring.cloud.client.ip-address}:${server.port}
server:
  port: 8765
  servlet : 
    context-path : /service-feign
spring:
  application:
    name: service-feign
  cloud : #指定配置中心
    config : 
      label: master
      profile: dev
      uri: http://localhost:8888/        
feign:
  hystrix:
    enabled: true
 