eureka:
  client:
    serviceUrl:
      defaultZone: http://admin:123123@eureka1:8001/eureka/,http://admin:123123@eureka2:8002/eureka/,http://admin:123123@eureka3:8003/eureka/
  instance:
    instanceId: ${spring.cloud.client.ip-address}:${server.port}
    prefer-ip-address: true #以IP地址注册到服务中心，相互注册使用IP地址
server:
  port: 8769
spring:
  application:
    name: service-zuul
zuul:
  #ignored-services: microservice-provider-user          # 需要忽视的服务(配置后将不会被路由)
  routes:
    api-a:
      path: /api-a/**
      service-id: service-hi
    api-b:
      path: /api-b/**
      service-id: service-feign
#是否开启重试功能
  retryable: true
#对当前服务的重试次数
ribbon: 
  MaxAutoRetries: 2
#切换相同Server的次数
  MaxAutoRetriesNextServer: 0      

#hystrix dashboard的信息收集频率，默认500毫秒
hystrix : 
  stream : 
    dashboard : 
      intervalInMilliseconds: 5000
management:
  endpoints:
    web:
      exposure:
        # * 在yaml 文件属于关键字，所以需要加引号 ,Actuator只暴露了health和info端点 ,暴露所有端点
        include: "*"          
